import type { GradeDef } from "./types";

export const grade12: GradeDef = {
  grade: 12,
  strands: [
    {
      id: "functions",
      name: "Advanced Functions",
      topics: [
        { name: "Function Composition", family: "composition", params: {} },
        { name: "Inverse Functions", family: "inverse-function", params: {} },
        { name: "Function Transformations", family: "function-transform", params: {} },
        { name: "Domain and Range", family: "domain-range", params: {} },
        { name: "Function Behaviour", family: "function-transform", params: {} },
      ],
    },
    {
      id: "functions",
      name: "Polynomial Functions",
      topics: [
        { name: "Polynomial Operations", family: "poly-mul", params: { kind: "mixed" } },
        { name: "Polynomial Division", family: "poly-division", params: {} },
        { name: "Synthetic Division", family: "poly-division", params: { synthetic: true } },
        { name: "Factor Theorem", family: "factor-theorem", params: {} },
        { name: "Remainder Theorem", family: "factor-theorem", params: {} },
        { name: "Polynomial Zeros", family: "factor-theorem", params: {} },
        { name: "Multiplicity", family: "factor-theorem", params: {} },
        { name: "Polynomial Graphs", family: "function-transform", params: {} },
        { name: "End Behaviour", family: "function-transform", params: {} },
      ],
    },
    {
      id: "functions",
      name: "Rational Functions",
      topics: [
        { name: "Rational Expressions", family: "rational-expression", params: { kind: "simplify" } },
        { name: "Rational Equations", family: "rational-expression", params: { kind: "solve" } },
        { name: "Restrictions", family: "rational-expression", params: { kind: "restrictions" } },
        { name: "Vertical Asymptotes", family: "rational-expression", params: { kind: "asymptotes" } },
        { name: "Horizontal Asymptotes", family: "rational-expression", params: { kind: "asymptotes" } },
        { name: "Holes", family: "rational-expression", params: { kind: "holes" } },
        { name: "Rational Graphs", family: "rational-expression", params: { kind: "mixed" } },
      ],
    },
    {
      id: "functions",
      name: "Radical Functions",
      topics: [
        { name: "Radical Expressions", family: "radical-expression", params: { kind: "simplify" } },
        { name: "Radical Equations", family: "radical-expression", params: { kind: "solve" } },
        { name: "Radical Functions", family: "radical-expression", params: { kind: "mixed" } },
        { name: "Radical Graphs", family: "function-transform", params: {} },
      ],
    },
    {
      id: "functions",
      name: "Exponential Functions",
      topics: [
        { name: "Exponential Growth", family: "exponential", params: { kind: "growth-decay" } },
        { name: "Exponential Decay", family: "exponential", params: { kind: "growth-decay" } },
        { name: "Transformations", family: "function-transform", params: {} },
        { name: "Exponential Equations", family: "exponential", params: { kind: "solve" } },
        { name: "Applications", family: "exponential", params: { kind: "mixed" } },
      ],
    },
    {
      id: "functions",
      name: "Logarithmic Functions",
      topics: [
        { name: "Logarithm Laws", family: "logarithm", params: { kind: "laws" } },
        { name: "Natural Logarithms", family: "logarithm", params: { kind: "natural" } },
        { name: "Common Logarithms", family: "logarithm", params: { kind: "eval" } },
        { name: "Logarithmic Equations", family: "logarithm", params: { kind: "solve" } },
        { name: "Logarithmic Inequalities", family: "logarithm", params: { kind: "solve" } },
        { name: "Logarithmic Graphs", family: "logarithm", params: { kind: "graph" } },
        { name: "Logarithmic Applications", family: "logarithm", params: { kind: "mixed" } },
      ],
    },
    {
      id: "trig",
      name: "Trigonometry",
      topics: [
        { name: "Unit Circle", family: "unit-circle", params: {} },
        { name: "Exact Values", family: "unit-circle", params: {} },
        { name: "Trigonometric Functions", family: "trig-graph", params: {} },
        { name: "Trigonometric Graphs", family: "trig-graph", params: {} },
        { name: "Transformations", family: "trig-graph", params: {} },
        { name: "Trigonometric Identities", family: "trig-identity", params: { level: 2 } },
        { name: "Trigonometric Equations", family: "trig-equation", params: {} },
        { name: "Compound Angle Identities", family: "trig-identity", params: { level: 2 } },
        { name: "Double Angle Identities", family: "trig-identity", params: { level: 2 } },
        { name: "Inverse Trigonometric Functions", family: "unit-circle", params: {} },
      ],
    },
    {
      id: "functions",
      name: "Sequences & Series",
      topics: [
        { name: "Infinite Geometric Series", family: "series", params: { kind: "infinite" } },
        { name: "Binomial Expansion", family: "binomial-theorem", params: {} },
        { name: "Binomial Theorem", family: "binomial-theorem", params: {} },
      ],
    },
    {
      id: "calculus",
      name: "Vectors",
      topics: [
        { name: "Vector Representation", family: "vectors", params: { kind: "components" } },
        { name: "Vector Addition", family: "vectors", params: { kind: "add" } },
        { name: "Vector Subtraction", family: "vectors", params: { kind: "add" } },
        { name: "Scalar Multiplication", family: "vectors", params: { kind: "components" } },
        { name: "Vector Magnitude", family: "vectors", params: { kind: "magnitude" } },
        { name: "Unit Vectors", family: "vectors", params: { kind: "magnitude" } },
        { name: "Vector Components", family: "vectors", params: { kind: "components" } },
        { name: "Dot Product", family: "vectors", params: { kind: "dot" } },
        { name: "Angle Between Vectors", family: "vectors", params: { kind: "angle" } },
        { name: "Applications", family: "vectors", params: { kind: "mixed" } },
      ],
    },
    {
      id: "calculus",
      name: "Calculus",
      topics: [
        { name: "Limits", family: "limits", params: {} },
        { name: "Evaluating Limits", family: "limits", params: {} },
        { name: "Continuity", family: "limits", params: {} },
        { name: "Derivative Concept", family: "derivative", params: { kind: "first-principles" } },
        { name: "Derivative from First Principles", family: "derivative", params: { kind: "first-principles" } },
        { name: "Power Rule", family: "derivative", params: { kind: "power" } },
        { name: "Product Rule", family: "derivative", params: { kind: "rules" } },
        { name: "Quotient Rule", family: "derivative", params: { kind: "rules" } },
        { name: "Chain Rule", family: "derivative", params: { kind: "chain" } },
        { name: "Derivatives of Exponential Functions", family: "derivative", params: { kind: "exp-log" } },
        { name: "Derivatives of Logarithmic Functions", family: "derivative", params: { kind: "exp-log" } },
        { name: "Derivatives of Trigonometric Functions", family: "derivative", params: { kind: "trig" } },
        { name: "Increasing and Decreasing Functions", family: "derivative-apps", params: { kind: "increasing" } },
        { name: "Critical Points", family: "derivative-apps", params: { kind: "critical" } },
        { name: "Maximum and Minimum", family: "derivative-apps", params: { kind: "critical" } },
        { name: "Optimization", family: "derivative-apps", params: { kind: "optimize" } },
        { name: "Antiderivatives", family: "integral", params: { kind: "antiderivative" } },
        { name: "Definite Integrals", family: "integral", params: { kind: "definite" } },
        { name: "Area Under Curves", family: "integral", params: { kind: "area" } },
        { name: "Fundamental Theorem of Calculus", family: "integral", params: { kind: "definite" } },
      ],
    },
  ],
};
