import type { GradeDef } from "./types";

export const grade3: GradeDef = {
  grade: 3,
  strands: [
    {
      id: "number",
      name: "Number Sense",
      topics: [
        // Both standards keep Grade 3 within 1,000 (CCSS 3.NBT, Ontario B1);
        // 10,000 was Grade 4 material arriving a year early (2026 audit).
        { name: "Place Value", family: "place-value", params: { max: 1000 } },
        { name: "Rounding", family: "rounding", params: { max: 1000 } },
        { name: "Comparing Numbers", family: "compare-numbers", params: { max: 1000 } },
        { name: "Number Lines", family: "number-line", params: { max: 1000 } },
        { name: "Multiples", family: "factors-multiples", params: { max: 100 } },
        { name: "Factors", family: "factors-multiples", params: { max: 100 } },
        { name: "Even and Odd Numbers", family: "odd-even", params: { max: 1000 } },
      ],
    },
    {
      id: "operations",
      name: "Addition & Subtraction",
      topics: [
        { name: "Multi-digit Addition", family: "multi-digit", params: { op: "add", digits: 3 } },
        { name: "Multi-digit Subtraction", family: "multi-digit", params: { op: "sub", digits: 3 } },
        { name: "Regrouping", family: "multi-digit", params: { op: "mixed", digits: 3 } },
        { name: "Estimation", family: "estimation", params: {} },
        { name: "Mental Math", family: "mental-math", params: { op: "mixed" } },
        { name: "Missing Numbers", family: "missing-number", params: { op: "mixed", max: 100 } },
      ],
    },
    {
      id: "operations",
      name: "Multiplication",
      topics: [
        { name: "Multiplication Concepts", family: "mult-facts", params: { tables: [2, 5, 10] } },
        { name: "Arrays", family: "mult-facts", params: { tables: [2, 3, 4, 5] } },
        { name: "Multiplication by 2", family: "mult-facts", params: { tables: [2] } },
        { name: "Multiplication by 3", family: "mult-facts", params: { tables: [3] } },
        { name: "Multiplication by 4", family: "mult-facts", params: { tables: [4] } },
        { name: "Multiplication by 5", family: "mult-facts", params: { tables: [5] } },
        { name: "Multiplication by 6", family: "mult-facts", params: { tables: [6] } },
        { name: "Multiplication by 7", family: "mult-facts", params: { tables: [7] } },
        { name: "Multiplication by 8", family: "mult-facts", params: { tables: [8] } },
        { name: "Multiplication by 9", family: "mult-facts", params: { tables: [9] } },
        { name: "Multiplication by 10", family: "mult-facts", params: { tables: [10] } },
        { name: "Multiplication Fluency", family: "mult-facts", params: { tables: [2, 3, 4, 5, 6, 7, 8, 9, 10] } },
      ],
    },
    {
      id: "operations",
      name: "Division",
      topics: [
        { name: "Division Concepts", family: "div-facts", params: { tables: [2, 5, 10] } },
        { name: "Equal Groups", family: "div-facts", params: { tables: [2, 3, 4, 5] } },
        { name: "Division Facts", family: "div-facts", params: { tables: [2, 3, 4, 5, 6, 7, 8, 9, 10] } },
        { name: "Division by 2", family: "div-facts", params: { tables: [2] } },
        { name: "Division by 3", family: "div-facts", params: { tables: [3] } },
        { name: "Division by 4", family: "div-facts", params: { tables: [4] } },
        { name: "Division by 5", family: "div-facts", params: { tables: [5] } },
        { name: "Division by 6", family: "div-facts", params: { tables: [6] } },
        { name: "Division by 7", family: "div-facts", params: { tables: [7] } },
        { name: "Division by 8", family: "div-facts", params: { tables: [8] } },
        { name: "Division by 9", family: "div-facts", params: { tables: [9] } },
        { name: "Division by 10", family: "div-facts", params: { tables: [10] } },
        { name: "Remainders", family: "long-division", params: {} },
      ],
    },
    {
      id: "fractions",
      name: "Fractions",
      topics: [
        { name: "Unit Fractions", family: "frac-identify", params: {} },
        { name: "Equivalent Fractions", family: "frac-equivalent", params: {} },
        { name: "Comparing Fractions", family: "frac-compare", params: {} },
        { name: "Fractions on Number Lines", family: "frac-number-line", params: {} },
        { name: "Numerators", family: "frac-identify", params: {} },
        { name: "Denominators", family: "frac-identify", params: {} },
        { name: "Fraction of a Set", family: "frac-identify", params: {} },
        { name: "Simple Fraction Addition", family: "frac-add-sub", params: { op: "add" } },
        { name: "Simple Fraction Subtraction", family: "frac-add-sub", params: { op: "sub" } },
      ],
    },
    {
      id: "measurement",
      name: "Measurement & Geometry",
      topics: [
        { name: "Length", family: "measure-units", params: { dim: "length" } },
        { name: "Mass", family: "measure-units", params: { dim: "mass" } },
        { name: "Capacity", family: "measure-units", params: { dim: "capacity" } },
        { name: "Time", family: "time", params: { kind: "mixed" } },
      ],
    },
    {
      id: "geometry",
      name: "Measurement & Geometry",
      topics: [
        { name: "Area", family: "perimeter-area", params: { shape: "rect" } },
        { name: "Perimeter", family: "perimeter-area", params: { shape: "rect" } },
        { name: "Angles", family: "angles", params: { kind: "identify" } },
        { name: "Right Angles", family: "angles", params: { kind: "identify" } },
        { name: "Quadrilaterals", family: "shapes-2d", params: {} },
        { name: "Triangles", family: "shapes-2d", params: {} },
        { name: "Symmetry", family: "symmetry", params: {} },
      ],
    },
    {
      id: "stats",
      name: "Data",
      topics: [
        { name: "Bar Graphs", family: "read-graph", params: { type: "bar" } },
        { name: "Line Plots", family: "read-graph", params: { type: "line-plot" } },
        { name: "Scaled Graphs", family: "read-graph", params: { type: "bar" } },
        { name: "Reading Data", family: "read-graph", params: { type: "mixed" } },
        { name: "Comparing Data", family: "read-graph", params: { type: "mixed" } },
      ],
    },
  ],
};
