import type { GradeDef } from "./types";

export const grade1: GradeDef = {
  grade: 1,
  strands: [
    {
      id: "number",
      name: "Number Sense",
      topics: [
        { name: "Counting", family: "counting", params: { max: 20 } },
        { name: "Number Recognition", family: "mc-bank", params: { bank: "number-writing" } },
        { name: "Number Writing", family: "mc-bank", params: { bank: "number-writing" } },
        { name: "One-to-One Correspondence", family: "counting", params: { max: 10 } },
        { name: "Comparing Numbers", family: "compare-numbers", params: { max: 20 } },
        { name: "Ordering Numbers", family: "order-numbers", params: { max: 20 } },
        { name: "Number Lines", family: "number-line", params: { max: 20 } },
        { name: "More and Less", family: "compare-numbers", params: { max: 10 } },
        { name: "Odd and Even Numbers", family: "odd-even", params: { max: 20 } },
        { name: "Place Value", family: "place-value", params: { max: 99 } },
        { name: "Tens and Ones", family: "place-value", params: { max: 99 } },
        { name: "Composing Numbers", family: "place-value", params: { max: 20 } },
        { name: "Decomposing Numbers", family: "place-value", params: { max: 20 } },
      ],
    },
    {
      id: "operations",
      name: "Addition & Subtraction",
      topics: [
        { name: "Addition Within 5", family: "add-sub", params: { op: "add", max: 5 } },
        { name: "Addition Within 10", family: "add-sub", params: { op: "add", max: 10 } },
        { name: "Addition Within 20", family: "add-sub", params: { op: "add", max: 20 } },
        { name: "Subtraction Within 5", family: "add-sub", params: { op: "sub", max: 5 } },
        { name: "Subtraction Within 10", family: "add-sub", params: { op: "sub", max: 10 } },
        { name: "Subtraction Within 20", family: "add-sub", params: { op: "sub", max: 20 } },
        { name: "Fact Families", family: "fact-family", params: { max: 20 } },
        { name: "Missing Addends", family: "missing-number", params: { op: "add", max: 20 } },
        { name: "Addition Strategies", family: "add-sub", params: { op: "add", max: 20 } },
        { name: "Subtraction Strategies", family: "add-sub", params: { op: "sub", max: 20 } },
        { name: "Mental Addition", family: "mental-math", params: { op: "add" } },
        { name: "Mental Subtraction", family: "mental-math", params: { op: "sub" } },
      ],
    },
    {
      id: "algebra",
      name: "Patterns",
      topics: [
        { name: "Repeating Patterns", family: "patterns", params: {} },
        { name: "Growing Patterns", family: "patterns", params: {} },
        { name: "Number Patterns", family: "patterns", params: {} },
        { name: "Missing Numbers", family: "missing-number", params: { op: "mixed", max: 20 } },
        { name: "Pattern Rules", family: "patterns", params: {} },
      ],
    },
    {
      id: "measurement",
      name: "Measurement",
      topics: [
        { name: "Comparing Length", family: "length-compare", params: {} },
        { name: "Measuring Length", family: "measure-units", params: { dim: "length" } },
        { name: "Non-standard Units", family: "length-compare", params: {} },
        { name: "Centimetres", family: "measure-units", params: { dim: "length" } },
        { name: "Time to the Hour", family: "time", params: { kind: "clock" } },
        { name: "Time to the Half Hour", family: "time", params: { kind: "half-hour" } },
        { name: "Calendar", family: "time", params: { kind: "calendar" } },
        { name: "Money", family: "money", params: { kind: "count" } },
      ],
    },
    {
      id: "geometry",
      name: "Geometry",
      topics: [
        { name: "2D Shapes", family: "shapes-2d", params: {} },
        { name: "3D Shapes", family: "shapes-3d", params: {} },
        { name: "Shape Attributes", family: "mc-bank", params: { bank: "shape-attributes" } },
        { name: "Sides", family: "shapes-2d", params: {} },
        { name: "Vertices", family: "shapes-2d", params: {} },
        { name: "Sorting Shapes", family: "mc-bank", params: { bank: "shape-attributes" } },
        { name: "Composing Shapes", family: "shapes-2d", params: {} },
        { name: "Decomposing Shapes", family: "shapes-2d", params: {} },
      ],
    },
    {
      id: "stats",
      name: "Data",
      topics: [
        { name: "Sorting Data", family: "mc-bank", params: { bank: "sorting-data" } },
        { name: "Categories", family: "mc-bank", params: { bank: "sorting-data" } },
        { name: "Picture Graphs", family: "read-graph", params: { type: "picture" } },
        { name: "Bar Graphs", family: "read-graph", params: { type: "bar" } },
        { name: "Reading Graphs", family: "read-graph", params: { type: "mixed" } },
      ],
    },
  ],
};
